### ISSUE TITLE
Where to put Discord Webhook in APK Editor studio

### ISSUE THREAD

**Issue by Proxy3200** [NullPounce/pounce-keys#12]
Hi I have downloaded apk editor studio and installed java as well. I download the discord apk from the releases and opened it with apk editor. It got opened. Now I am unable to find where to put discord web hook URL. I have searched using settings search but unable to find it. I have opened Contents of app and it showed me this folder(below Screenshot). I am unable to find messagesender.java file here. Where to add discord web hook please help.
![ApkEditorStudio Contents](https://github.com/NullPounce/pounce-keys/assets/130583428/1076cb98-1ceb-4c2c-83b7-804e130a541d)

**Comment by NullPounce** [comment]
thank you for the notice, when I have time I'll dig through my source code. :) Gmail version is the best one in my opinion.

**Comment by Proxy3200** [comment]
The same is the case with the gmail version apk. It shows similar content folder in apk editor studio and I am unable to find using search settings as well where to put my gmail and app password

**Comment by rohittotlani** [comment]
Yes Getting the same problem with gmail version apk as well. Unable to find where to put my gmail id and app password.
@Proxy3200 Were you able to find a solution?
@NullPounce Please help on this.

**Comment by NullPounce** [comment]
check the new update that includes a builder for ip, gmail, and discord or use https://github.com/AndnixSH/APKToolGUI
