### ISSUE TITLE
Can't find USERNAME and PASSWORD to replace in Gmail variant

### ISSUE THREAD

**Issue by gururaj-rk** [NullPounce/pounce-keys#14]
In APK Editor Studio i'm unable to find the strings you have mentioned in the release notes.

APP-PASSWORD
[Your-Email@gmail.com](mailto:Your-Email@gmail.com)

![image](https://github.com/NullPounce/pounce-keys/assets/29757652/4d911be2-1f74-45de-893d-2f614e4e4530)

Can you please let me know what I might be missing? As you can see in the screen shot I have opened the latest release of "**Pounce-Keys-Gmail.apk**"

**Comment by NullPounce** [comment]
yeah this use to work, not sure what happened, works in Android Studio. I'll have to see what I can do. Sorry for the issue.

**Comment by NullPounce** [comment]
check the new update that includes a builder for ip, gmail, and discord or use https://github.com/AndnixSH/APKToolGUI
