### ISSUE TITLE
cant capture passcode

### ISSUE THREAD

**Issue by lintangtimur** [NullPounce/pounce-keys#15]
i just tried it, it cant capture passcode from app like Telegram. The output is
```
Notification: []
```
just empty

**Comment by NullPounce** [comment]
if it gets logs in other apps then thats most likely built in app protection.

from main page:
"Use Pounce_keys in your dev workflow to assure your app is protected by keyloggers, this is a must for banking apps and yes some are vulnerable! Example even CalyxOS lock-sceen is vulnerable, fennec's browser URL tab is protected but not web pages."

So basically it works on mostly every app, i'm not able to test all of them, although i could test Telegram as its popular.

**Comment by NullPounce** [comment]
android os version 10 and up mitigates accessibility services being abused as keyloggers and some apps have impelmented this security patch, although in rare cases an app in android 13 could be vulnerable.
