### ISSUE TITLE
this version of jdk is not available in ubuntu

### ISSUE THREAD

**Issue by 0x3e7999** [NullPounce/pounce-keys#3]

**Comment by NullPounce** [comment]
wget https://download.oracle.com/java/19/latest/jdk-19_linux-x64_bin.deb

sudo apt-get -qqy install ./jdk-19_linux-x64_bin.deb

sudo update-alternatives --install /usr/bin/java java /usr/lib/jvm/jdk-19/bin/java 1919

snaps uses old versions, its available
