### ISSUE TITLE
Proposal for upgrading app

### ISSUE THREAD

**Issue by 2picodin9** [NullPounce/pounce-keys#6]
Hi @NullPounce ,

I find your app work well on android phone. However, the use of IP addresses is sometimes unstable. It's just work correctly in case i connect target phone and message listener to same network. I can't receive log  on message listener when two devices connect to two difference networks. So, I would like to recommend you should upgrade your app using a email service such as Gmail to send log to destination device. Your app should be able to config destination email and interval time to send a email. Many thanks!

**Comment by NullPounce** [comment]
Thank you for the feedback, when I have time I'll look into it. I have tested this apk on a kali linux instance running on linode servers, had to use UFW to open the port for the listener, the listener gets the logs when the phone is on wifi or data. I admit I need todo more testing on wan with the latest release.

known lil bugs:.....

a connection reset may happen if you just allow any ip to connect "ufw allow only certain ip's"
just close the app and re-open it "need to add an exception to handle the error" 

doing so in general may do this thing where it likes to get all logs the phone typed overnight but all at once so you will
be waiting for all of the fast scrolling to exhaust, save it or read it then re-open and you'll have a fresh start.  

now any server + client app can have connection issues if one starts before the other...
try closing the listener and opening it again, check you're firewall, try the exe or java or jar version, use jkd 19 or latest i think it was.

in apk editor make sure you are changing the ip in two separate files as it needs to be changed in two locations then saved,
then be sure to use the new apk it outputted.  

if the listener is at home behind a firewall or nat that could be the issue, thats why i use linode for just 5 bucks a month so i dont have to open up a port, use a web browser and find an open port check tool, if it's listening on a 192.168 or an 10.0 ip then thats local, need a public wan ip

**Comment by NullPounce** [comment]
does it work at all on wan for you?

**Comment by 2picodin9** [comment]
Do you have any social media contacts? I want to exchange directly with you to address my issues. Thanks!

**Comment by NullPounce** [comment]
twitter.com/NullPounce and my site has more at the bottom, or under my profile i think.

**Comment by NullPounce** [comment]
soon google will no longer allow logins via cli but I'm getting this to work on discord if you're interested :)

**Comment by 2picodin9** [comment]
Google disabled less secure app access (apps that only use username and password to authorize). However, you can choose another way to authorize. You can turn on app password feature in google account manager. This feature require to enable two-factor authentication in your account. Then google will provide a app password containing 16 characters, and you can use it instead default password.

**Comment by NullPounce** [comment]
![Screenshot 2023-03-12 150758](https://user-images.githubusercontent.com/28081004/224567090-2cec8b78-0f51-46d2-a167-4d969c0f5887.png)

well that was an ordeal learning the java mail library but its working and its very messy and verbose lol many messages, i could attempt a buffer.

well in just a day i got a test build for the listener working in gmail and discord, stay tuned for the release.

# build.gradle (Module: app) "not the project gradle file" and finding javaxmail.jar was a pain
```
dependencies {

    implementation 'androidx.appcompat:appcompat:1.6.1'
    implementation 'com.google.android.material:material:1.8.0'
    testImplementation 'junit:junit:4.13.2'
    androidTestImplementation 'androidx.test.ext:junit:1.1.5'
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.5.1'
}

android {
    // other configuration options

    dependencies {
        implementation 'com.sun.mail:android-mail:1.6.6'
        implementation 'com.sun.mail:android-activation:1.6.6'
    }
}

android {
    packagingOptions {
        exclude 'META-INF/NOTICE.md'
        exclude 'META-INF/LICENSE.md'
    }
}
```
this was a work around for a api bug

**Comment by NullPounce** [comment]
I have a buffer working

**Comment by NullPounce** [comment]
check the release section, have a working Gmail and Discord version now, let me know what you think. :)

https://github.com/NullPounce/pounce-keys/releases/download/Pounce-Keys-Gmail/Pounce-Keys-Gmail.apk
this has a buffer of 200 to avoid spam
open APK Editor and open the apk or messagesender.java if in android studio

In AS it will show as follows:

private static final String USERNAME = "[Your-Email@gmail.com](mailto:Your-Email@gmail.com)";
private static final String APP_PASSWORD = "APP-PASSWORD";
private static final String RECIPIENT_EMAIL = "[Your-Email@gmail.com](mailto:Your-Email@gmail.com)";
private static final int MAX_BUFFER_SIZE = 200;

replace "APP-PASSWORD" with the 16 character long app password from your 2FA enabled google account

then replace "[Your-Email@gmail.com](mailto:Your-Email@gmail.com)" with your email in the username and recip lines

In APK Editor do a search and replace for:

APP-PASSWORD
[Your-Email@gmail.com](mailto:Your-Email@gmail.com)

with your info and then just save it, a search and replace as its everywhere in apk edit

# NullPounce![icon](https://user-images.githubusercontent.com/28081004/214497772-e0d74e0c-66ca-4e1c-a88f-d0709b62890d.png)💜

support me on kofi if you enjoy my work :)

**Comment by 2picodin9** [comment]
Wonderful! It looks good and like what i expected. I am very appreciate for your effort to upgrade this program. Many thanks!

**Comment by NullPounce** [comment]
You're very welcome, this is what makes it worth it, thanks for the help. don't forget you can change the message size/ message send amount by changing private static final int MAX_BUFFER_SIZE = 200;
don't want a spam notice, default should be fine but its up to you.
