### ISSUE TITLE
can find  "192.168.0.135" when i open up the apk 

### ISSUE THREAD

**Issue by Cruzstyle** [NullPounce/pounce-keys#8]
hello Null!
I have the app set up on wsl and android apk editor installed too. However, anytime I open up the apk in the editor studio I don't seem to find  "192.168.0.135" or any of the smali files mainactivity and messegesener to replace with my IP. how can I go about it to set up fully?

**Comment by Pixel2075** [comment]
same

**Comment by MohamedCS1** [comment]
+1

**Comment by NullPounce** [comment]
check the new update that includes a builder for ip, gmail, and discord or use https://github.com/AndnixSH/APKToolGUI
