### ISSUE TITLE
JDK 19 Link Down.

### ISSUE THREAD

**Issue by IncasedDevelopment** [NullPounce/pounce-keys#9]
## Issue Description: Update broken download link for JDK-19 installation

**Background:**
The author of the project has included a command in the documentation for downloading the JDK-19 Linux x64 binary package. However, the provided download link is no longer valid and results in a 404 error. The command that needs to be updated is as follows:

Current command:
`wget https://download.oracle.com/java/19/latest/jdk-19_linux-x64_bin.deb`

**Issue:**
The current command to download the JDK-19 Linux x64 binary package is no longer functional due to an outdated download link. The link provided returns a 404 error, indicating that the resource does not exist. 

**Proposed Solution:**
The command should be updated with the corrected download link to ensure that users can successfully download the JDK-19 Linux x64 binary package. The updated command should be as follows:

Updated command:
`wget https://download.oracle.com/java/19/archive/jdk-19_linux-x64_bin.deb`

By replacing "latest" with "archive" in the download link, users will be directed to the correct location to download the JDK-19 Linux x64 binary package.

**Steps to Reproduce:**
1. Access the project documentation.
2. Locate the section related to JDK-19 installation.
3. Identify the command provided for downloading the JDK-19 Linux x64 binary package.
4. Execute the command.
5. Observe that the download fails with a 404 error.

**Expected Behavior:**
After updating the command with the corrected download link, users should be able to successfully download the JDK-19 Linux x64 binary package without encountering any errors.

Please let me know if you need any further assistance or if there are any additional details you would like to include in the issue description.

You can copy the above markdown and use it for your GitHub issue. Let me know if you need any further assistance!

**Comment by NullPounce** [comment]
thank you for the info i have updated the url.
